[build]
  publish = "webgame"
  functions = "server"
  command = "npm --prefix server ci && npm --prefix webgame ci && npm --prefix webgame run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "server"